name: docker-lint
on:
  pull_request:
    branches:
      - '*'
jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v3
        - uses: hadolint/hadolint-action@v2.0.0
          with:
            dockerfile: docker/Dockerfile